language: php

sudo: false

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: always
