language: php

sudo: false

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - mkdir -p build/tests/
  - vendor/bin/parallel-lint src/ tests/
  - vendor/bin/phpcs -sp src/ tests/
  - vendor/bin/php-cs-fixer fix -v --dry-run
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpstan.phar analyze -l max src/ tests/
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/tests/coverage.xml

notifications:
  email:
    on_success: never
    on_failure: always
